### ISSUE TITLE
Leaderboard Secondary Sort not by Time Taken

### ISSUE THREAD

**Issue by aaelfe** [coopersully/coople-issues#1]
It seems that when users are tied on the leaderboard for the number of guesses it took them, rankings are then sorted from first to complete to last to complete. It seems intuitive for rankings to sort by time taken to complete the game if the number of guesses is the same.

**Comment by coopersully** [comment]
They were completely sorted by daily score. To solve this issue, I've made it where you can sort by any property of the user's game session, but daily score is default. I've also made time more penalizing to your daily score.
